---
name: Benchmark
on:
  workflow_dispatch: {}
  push: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: ./upstream/tests/docker/Dockerfile
          target: rp-storage-tool
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-with-depot:
    name: (Depot) Release
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          context: ./upstream/tests/docker/Dockerfile
          target: rp-storage-tool
          platforms: linux/amd64,linux/arm64
